spring:
  application:
    name: promotion-service
  threads:
    virtual:
      enabled: true
  config:
    import: [ "optional:nacos:shared-spring.yaml", "optional:nacos:shared-redis.yaml", "optional:nacos:shared-rabbitmq.yaml", "optional:nacos:shared-logs.yaml", "optional:nacos:${spring.application.name}.yaml" ]
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery: { namespace: public, group: DEFAULT_GROUP }
      config: { namespace: public, group: DEFAULT_GROUP, file-extension: yaml }
---
spring:
  config:
    activate: { on-profile: local }
    import: [ "optional:nacos:shared-spring.yaml", "optional:nacos:shared-redis.yaml", "optional:nacos:shared-rabbitmq.yaml", "optional:nacos:shared-logs.yaml", "optional:nacos:${spring.application.name}.yaml" ]
  cloud: { nacos: { server-addr: tj-nacos:8848 } }
