server:
  port: 10011
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TJ_MYSQL_HOST:127.0.0.1}:${TJ_MYSQL_PORT:3306}/tj_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${TJ_MYSQL_USERNAME:root}
    password: ${TJ_MYSQL_PASSWORD:root}
    hikari:
      pool-name: AuthHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  grpc:
    server:
      port: 9090

  cloud:
    loadbalancer:
      nacos:
        enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.tjauth.Entity
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  packages-to-scan: com.example.tjauth.Controller

tj:
  auth:
    jwt: # 部署使用 Docker Compose挂载密钥
      # 私钥路径（classpath 或绝对路径）
      private-key-path: classpath:keys/private_key.pem
      # 公钥路径（可选，从私钥推导也行）
      public-key-path: classpath:keys/public_key.pem
      # 算法（RS256）
      algorithm: RS256
      # 签发者
      issuer: tj-auth
      token-ttl: 30m
      refresh-ttl: 7d
    headers:
      authorization: Authorization
      refresh: Refresh
    exclude-path:
      - /error/**
      - /accounts/login
      - /accounts/admin/login
      - /accounts/refresh
      - /jwks
      - /v3/api-docs/**

#部署时docker compose内： (关联secret)
# services:
#  tj-auth:
#    environment:
#      - TJ_JWT_SECRET=X7jK9pL2mN4qR8sT1wW3yZ5aB6cD0eF7gH9iJ2kM4nO=