spring:
  application:
    name: TJ_Project_Api-auth
  profiles:
    active: local   # 默认使用本地开发环境

---
# ========== 本地开发环境 ==========
spring:
  config:
    activate:
      on-profile: local
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379
          database: 0

---
# ========== Docker 部署环境 ==========
spring:
  config:
    activate:
      on-profile: docker
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://tj-redis:6379"
          database: 0