spring:
  application:
    name: auth-service

  threads:
    virtual:
      enabled: true

  config:
    import:
      - optional:nacos:shared-spring.yaml
      - optional:nacos:shared-redis.yaml
      - optional:nacos:shared-logs.yaml
      - optional:nacos:${spring.application.name}.yaml

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery: { namespace: public, group: DEFAULT_GROUP }
      config: { namespace: public, group: DEFAULT_GROUP, file-extension: yaml }

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      server-addr: tj-nacos:8848